# Generated by Django 4.2.7 on 2023-11-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusers',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='appusers',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this User belongs to.', related_name='Userapp_relations', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='appusers',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='Userapp_relations', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
